### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ys1998** [ys1998/spsim#9]
Branch prediction : @rs9899 @ys1998 
- [x] Branch predictor
- [x] Flusher
- [x] Integrate flusher with other entities

Load/store : @Naman-ntc @Ug48 @sharvik-mital 
- [x] Address queue
- [x] Memory stage and related handling

Common
- [x] Proper updating and displaying of integer registers
- [x] Update parser for new type of instructions
- [x] Report

Feel free to add more.
